server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: authsessionstore

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/auth_session_store}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 3000ms
      repositories:
        enabled: false

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  health:
    mail:
      enabled: false

app:
  jwt:
    secret: ${JWT_SECRET:NzQ5YmY2NzAtYmFiYS00NTEwLWEwYjItYmQyNmE4YWRkNzYzLTY0YmY2NzAtYmFiYS00NTEwLWEwYjItYmQyNmE4YWRkNzYz}
    access-token-expiration-minutes: ${JWT_ACCESS_EXPIRATION_MINUTES:15}
    refresh-token-expiration-days: ${JWT_REFRESH_EXPIRATION_DAYS:7}

  otp:
    expiration-minutes: ${OTP_EXPIRATION_MINUTES:5}

  password-reset:
    expiration-minutes: ${PASSWORD_RESET_EXPIRATION_MINUTES:15}

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
    org.springframework.data.redis.repository.configuration: ERROR